# Generated by Django 4.2 on 2025-02-05 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.userprofile', verbose_name='comment_user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
