# Generated by Django 4.2 on 2025-02-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_parent_comment_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='home/user_img/default.png', null=True, upload_to='home/user_img/%Y/%m', verbose_name='头像'),
        ),
    ]
